### ISSUE TITLE
Product is not adding

### ISSUE THREAD

**Issue by rsoorajs** [pkspyder007/Excalibur#11]
i did exactly what you mentioned the read me.successfully connected to the database.i put my gclient id and secret,then gave my new gmail id and password.but when adding a product,the loading button button is keep spinning,thats all.nothing hapoening.
still something is wrong
you can check that is in my website 

https://ba65e71e6ba5.ngrok.io

also when i am trying to logout,it always go for local host ip,instead of my ip..if you can fix that too.

![IMG_20200930_154327_063](https://user-images.githubusercontent.com/20116017/94673007-b3d18400-0333-11eb-9337-1daa8079ed83.jpg)

**Comment by telegrambotdev** [comment]
![IMG_20200930_155813_139](https://user-images.githubusercontent.com/20116017/94674453-d06ebb80-0335-11eb-9ebc-793a7afb6571.jpg)

**Comment by pkspyder007** [comment]
@telegrambotdev this project was not setup for deployment. 
And moreover the scrapping logic might have become Obselute. 
I'll look into the issue and update the repo accordingly.

**Comment by telegrambotdev** [comment]
> @telegrambotdev this project was not setup for deployment.
> And moreover the scrapping logic might have become Obselute.
> I'll look into the issue and update the repo accordingly.

kindly update the repo.its an amazing code,which we need most

also add an option to get alert for any price drop,without mentioning the price.

Thank you

**Comment by pkspyder007** [comment]
@telegrambotdev  i'll surely update the repo if it helps you. give me some time to update and if you want to contribute feel free to create a PR.

**Comment by telegrambotdev** [comment]
> @telegrambotdev i'll surely update the repo if it helps you. give me some time to update and if you want to contribute feel free to create a PR.

i just made 2 PR.ok,update the repo when you are free,keep coding bro.your work is amazing.

**Comment by telegrambotdev** [comment]
Also if you can add an option to put mongodb url as env var too,because many people use online mongodb,then they can also use your code.just a suggetion,not so important.your default,mongodb working fine already

**Comment by pkspyder007** [comment]
> Also if you can add an option to put mongodb url as env var too,because many people use online mongodb,then they can also use your code.just a suggetion,not so important.your default,mongodb is already working fine.

Yes we can do that as well
